#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

manifest:
  version: "0.13"

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
<<<<<<< HEAD
      revision: v3.3.0
=======
      revision: v3.3.0-rc1
>>>>>>> 646f787 (manifest: Update ncs to v3.3.0-rc1)
      import: true

    - name: edge-impulse-sdk-zephyr
      url: https://github.com/edgeimpulse/edge-impulse-sdk-zephyr
      path: modules/edge-impulse-sdk-zephyr
      revision: v1.88.1
      west-commands: west/west-commands.yml

  self:
    path: edge-ai
